### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by cbenhagen** [auth0/auth0-flutter#164]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Web is not supported

### Describe the ideal solution

Wrap existing web implementation.

**Comment by stevehobbsdev** [comment]
Thanks for raising this. We do have tentative plans on our roadmap to add web support in the coming months balanced against our other external and internal commitments for the end of the year. However, others have asked for this and it is on our roadmap. Thanks for your support!

**Comment by stevehobbsdev** [comment]
FYI Web Support is now added in [v1.2.0](https://github.com/auth0/auth0-flutter/releases/tag/v1.2.0)! Feel free to try it out and let us know if you have any feedback.
