### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by cbenhagen** [auth0/auth0-flutter#167]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Windows is not supported

### Describe the ideal solution

Add Windows implementation

**Comment by stevehobbsdev** [comment]
We don't have any plans to add support for Windows currently but could change as we receive more feedback. However, this package supports [federated plugins](https://docs.flutter.dev/development/packages-and-plugins/developing-packages#federated-plugins) and so this functionality could be added by the community.

Thanks for your support!
