### ISSUE TITLE
Web support

### ISSUE THREAD

**Issue by mngphm** [auth0/auth0-flutter#169]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Any ETA for adding web support?

### Describe the ideal solution

Add web support to auth0-flutter sdk

**Comment by Widcket** [comment]
Hi @mngphm, thanks for raising this.

We do have tentative plans to explore adding support for web. I can't confirm if it will happen at all ATM or share an ETA, unfortunately. I'll leave this issue open and circle back once we have something to share.

**Comment by mngphm** [comment]
hi @Widcket 
thanks for feedback. Is there a documentation how i can achieve flutter web integration with auth0 without the SDK. Can you point me to the right direction?

**Comment by Widcket** [comment]
Since Flutter for web supports interop with JS, you could use our SDK for SPAs: https://github.com/auth0/auth0-spa-js/.

**Comment by JCQuintas** [comment]
It would be really helpful to have auth0 flutter with "native" support for web. Right now the amount of boilerplate I need to write for it to work properly is quite big...

**Comment by llaski** [comment]
+1 We are also running into this issue and using the JS SDK to solve this is a huge hassle and been challenging for us.

**Comment by ghenry** [comment]
I'd love this too. If I have to manage the Web bit myself, there's no point using flutter to handle this all for me.

**Comment by tillguthardt** [comment]
Auth0 for flutter web would be really very cool.

**Comment by tillguthardt** [comment]
Auth0 for flutter web would be very helpful.

**Comment by adnankhan74444** [comment]
I am also looking for web support.

@Widcket 
Any update on this please ?

**Comment by alexboulay** [comment]
Also looking for support with this. Thank you.

**Comment by Widcket** [comment]
> We do have tentative plans to explore adding support for web. I can't confirm if it will happen at all ATM or share an ETA, unfortunately.

@adnankhan74444 I'm afraid this is still the case.

**Comment by adnankhan74444** [comment]
Their are lot of people are waiting for web support ..

@Widcket

**Comment by Painwraith** [comment]
seeking web support as well.

**Comment by michaldev** [comment]
It will be helpful.

**Comment by Widcket** [comment]
Hi all, this is being worked on at the moment. No date yet I can share, though.

**Comment by keepersmith** [comment]
+1 to providing web support.
One of the main reasons to use flutter in the first place is to chase the dream of one codebase for all (relevant) platforms.
Please add web (and desktop) support.
Thanks!

**Comment by ghenry** [comment]
Congratulations!

**Comment by Widcket** [comment]
@tom-bailey-om good catch, thank you! https://github.com/auth0/auth0-flutter/pull/254 fixes this.

**Comment by Widcket** [comment]
Web support is now available in [v1.2.0](https://github.com/auth0/auth0-flutter/releases/tag/v1.2.0)!

I'll go ahead and close this issue. If you encounter any bugs, please feel free to open a new one.
