### ISSUE TITLE
Login/Forgot password screens have autocorrect enabled on email field

### ISSUE THREAD

**Issue by LampeMW** [auth0/auth0-flutter#171]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When attempting to login or reset password on the webview that pops up, autocorrect is enabled and makes it very difficult to enter your email address properly.

### Reproduction

1. call `await auth0.webAuthentication().login();`
2. On the corresponding view that appears, type in your email address

### auth0_flutter version

1.0.1

### Flutter version

3.3.3

### Platform

iOS

### Platform version(s)

13.7

**Comment by Widcket** [comment]
Hi @LampeMW, thanks for raising this.

What you describe seems to be an issue in the Universal Login page, which is out of the scope of this SDK. I'd suggest opening a [support ticket ](https://support.auth0.com/) to get it routed to the right team.
