### ISSUE TITLE
Android Universal Web Authentication failing when using the plugin

### ISSUE THREAD

**Issue by arnav-ladkat** [auth0/auth0-flutter#183]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We are currently building an app with Auth0 for Authentication, with flavours configured for Android and iOS.
I have followed all the instructions mentioned in the [Getting Started](https://auth0.com/docs/quickstart/native/flutter/interactive) document.

This is what my build Gradle file looks like 

```
defaultConfig {
// Other config items
        manifestPlaceholders += [auth0Domain: "@string/com_auth0_domain", auth0Scheme: "@string/com_auth0_scheme"]
    }

    buildTypes {
        release {
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
            signingConfig signingConfigs.debug
        }
    }

    flavorDimensions "default"

    productFlavors {
        staging {
            dimension "default"
            resValue "string", "app_name", "Appname"
            applicationIdSuffix ".stg"
            manifestPlaceholders += [auth0Domain: "@string/com_auth0_domain", auth0Scheme: "@string/com_auth0_scheme"]
        }
        production {
            dimension "default"
            resValue "string", "app_name", "Appname"
            applicationIdSuffix ""
            manifestPlaceholders += [auth0Domain: "@string/com_auth0_domain", auth0Scheme: "@string/com_auth0_scheme"]
        }
    }
```

I have added the required  values in `android/app/src/main/res/values/strings.xml`
and am also explicitly declaring the scheme for authentication

```
credentials = await auth0.webAuthentication(scheme: 'https').login(
          scopes: {
            'profile',
            'email',
            'offline_access',
            'openid'
          },
          parameters: {
            'prompt': 'login',
            'audience': '$audience'
          });
```

The view technical details section shows 1 of the 3 errors mentioned below:
### First
> Password login via OIDC-conformant clients with externally-hosted login pages is unsupported. Alternatively, login could have been initiated from the wrong place (e.g., a bookmark).
### Second
>**NOT FOUND** - The webpage just mentions not found.
### Third
>Failed to load previous state.

We face these even when implementing the auth0 tutorial from scratch for Android.

### Reproduction

We face these even when implementing the auth0 tutorial from scratch for Android.
1. Setup Auth0 Application
2. Add Callback URLs
3. Update Build Gradle : minimum android version and manifest placeholders for default as well as flavours, 
4. Add values in  `android/app/src/main/res/values/strings.xml`.
5. Specify Scheme in the WebAuth function.

### auth0_flutter version

1.0.2

### Flutter version

3.3.4

### Platform

Android

### Platform version(s)

Android 12 and 13

**Comment by Widcket** [comment]
Hi @Arnav-Ladkat, thanks for raising this.

Can you reproduce this in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) without setting up flavors?

**Comment by Arnav-Ladkat** [comment]
Hey @Widcket, 
Thanks for your prompt response

Yes
1. This can be reproduced in the sample app without setting up flavours
2. it can also be replicated after following the instructions on the  [Getting Started](https://auth0.com/docs/quickstart/native/flutter/interactive) document. (without using flavours)

**Comment by Widcket** [comment]
@Arnav-Ladkat I just downloaded the sample app, set it up according to its [README](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample#readme), and was unable to reproduce.

https://user-images.githubusercontent.com/5055789/201228634-24863b67-816a-4f29-9d8c-f33649882eb0.mov

**Comment by arnav-ladkat** [comment]
Hey @Widcket, it works when the scheme is set to `demo` or `app`,  but for `https` it does NOT work.
Can you please try it with the scheme set `https` ?

**Comment by Widcket** [comment]
Hi @arnav-ladkat, I set up App Links and tested it using an Android API 30 emulator. I was unable to reproduce:

https://user-images.githubusercontent.com/5055789/201454083-cda1cd78-0051-402d-a7fc-e9fa9d6c65b2.mov

These are the changes to the app manifest:

<img width="642" alt="Screen Shot 2022-11-12 at 00 17 57" src="https://user-images.githubusercontent.com/5055789/201454053-bd2a4a9a-1992-45b3-9689-999e734ef4d2.png">

I also configured the Auth0 application to use App Links: https://auth0.com/docs/get-started/applications/enable-android-app-links-support

**Comment by arnav-ladkat** [comment]
Hey @Widcket , 
I see you are using app links. Can you please try it without App links, Just using `HTTPS` as a scheme for authentication?

I have accommodated these changes in my sample app as well.
1. Android Manifest 
<img width="624" alt="Screenshot 2022-11-13 at 7 55 44 PM" src="https://user-images.githubusercontent.com/84362194/201526890-de441fe6-a369-48b5-af09-aedc851ba3b1.png">

2. strings.xml
<img width="492" alt="Screenshot 2022-11-13 at 7 58 00 PM" src="https://user-images.githubusercontent.com/84362194/201526972-cd46d311-18f5-4a65-872f-866bf5207fa3.png">

3. Auth0 Callback and logout URLs:
```
https://{AUTH0Domain}/android/com.auth0.sample/callback, 
com.auth0.sample://{AUTH0Domain}/ios/com.auth0.sample/callback
```
Where i have replaced '{AUTH0Domain}' with my auth0 app domain


Bug in the Sample App
https://user-images.githubusercontent.com/84362194/201527852-54e7a58b-2c37-443a-a612-6307da4b4ed9.mp4



 Please let me know if I am missing anything
 Thanks

**Comment by Widcket** [comment]
Hi @arnav-ladkat, 

> I see you are using app links. Can you please try it without App links, Just using HTTPS as a scheme for authentication?

Using the `https` scheme on Android [requires App Links](https://github.com/auth0/Auth0.Android#a-note-about-app-deep-linking). Note that it's possible that the browser [may still block the redirect](https://bugs.chromium.org/p/chromium/issues/detail?id=738724). I'd suggest simply using a custom scheme instead of `https`.

**Comment by arnav-ladkat** [comment]
Understood
Thanks for the details @Widcket ,
I'll either set up app links or use a custom scheme instead of `https`.

I'm curious since the previous[ Flutter Auth0](https://auth0.com/blog/get-started-with-flutter-authentication/) documentation allowed support for `https` as a callback scheme for android without having to set up App Links. In this case, we could use Deep Linking for in-app routing.

Can such a use case be added to this plugin? Would it be open to contributions?

**Comment by Widcket** [comment]
That blog post predates this SDK, and uses a third-party library. Note that on newer versions of Android you can't really use `https` (Web Links) without App Links. See **https://developer.android.com/training/app-links#web-links**
