### ISSUE TITLE
Access Token 

### ISSUE THREAD

**Issue by ghenry** [auth0/auth0-flutter#185]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi,

All auth0 docs point me to this sdk for flutter but I can't see how to do https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-proof-key-for-code-exchange-pkce

Thanks,
Gavin. 

### Reproduction

See above 

### auth0_flutter version

Main 

### Flutter version

Stable 

### Platform

Android, iOS

### Platform version(s)

v16 and 33

**Comment by Widcket** [comment]
Hi @ghenry, thanks for raising this. 

I'm not sure I follow, can you please explain what exactly is the issue you're experiencing?

**Comment by ghenry** [comment]
Hi @Widcket 

Thanks for your reply. I'm trying to understand if I can use this SDK to login the user, but also get them to authorize this native app to act on their behalf and get auth0 to issue an access token etc. I can use with our own API. This:

https://auth0.com/docs/get-started/authentication-and-authorization-flow/call-your-api-using-the-authorization-code-flow-with-pkce

All the docs ask you to use the correct native SDK. I'm using Flutter, so I go to use this but it only supports login?

Thanks,
Gavin.

**Comment by Widcket** [comment]
Hi, 

Yes, after logging in you get a `Credentials` instance which contains an access token and an ID token (which in turn contains the user profile data, that is exposed through the `user` property as well).

In order to be able to use the access token to access a protected API, you need to pass the Auth0 API identifier of your API as the audience value when logging in.

See https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md#specifying-an-audience-value

**Comment by ghenry** [comment]
Thanks. I actually just read about the Auth0 API identifier yesterday and when I read the auth0-flutter docs last week it didn't register what I was reading! Excellent, I know how it all fits together now.

Much appreciated for your detailed reply.

Gavin.

**Comment by ghenry** [comment]
Hi,

Got this all working now, but do I need to store my accessToken securely, say using, flutter_secure_storage, or is CredentialManager handling that and it will be save to the device?

Thanks.

**Comment by Widcket** [comment]
The SDK automatically stores it after login. See https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#logging-in

<img width="1053" alt="Screen Shot 2022-12-01 at 09 30 56" src="https://user-images.githubusercontent.com/5055789/205053882-6aec8b3c-3f56-4781-a4b8-acfb59fef01c.png">

**Comment by ghenry** [comment]
Hi @Widcket 

Thanks. The reason I asked it is that's the instance, but doesn't mention or imply persistent storage. If it does, what is it using on iOS and Android for this.

When I normally use Ory Hydra and Flutter AppAuth, I save the token with flutter_secure_storage. Your docs do say it's encrypted.

Gavin.

**Comment by Widcket** [comment]
The Flutter SDK wraps the native SDKs for Android and iOS: [Auth0.Android](https://github.com/auth0/Auth0.Android) and [Auth0.swift](https://github.com/auth0/Auth0.swift).

Auth0.Android exposes two Credentials Managers, one that uses encryption (`SecureCredentialsManager`) and one that doesn't (`CredentialsManager`). The Flutter SDK uses the secure one. You can check [its implementation](https://github.com/auth0/Auth0.Android/blob/main/auth0/src/main/java/com/auth0/android/authentication/storage/SecureCredentialsManager.kt) to learn more about the encryption it uses.

Auth0.swift's [Credentials Manager](https://auth0.github.io/Auth0.swift/documentation/auth0/credentialsmanager/) stores the tokens in the system Keychain, using our [SimpleKeychain](https://github.com/auth0/SimpleKeychain) library as the storage layer. You can learn more about the encryption the system Keychain uses [here](https://support.apple.com/guide/security/keychain-data-protection-secb0694df1a/web).

**Comment by ghenry** [comment]
Perfect!

Maybe this would be a good addition for a copy and paste into the docs?

Thanks for taking the time to reply once again. I can relax now. This SDK saves a ton of work!!! I wish it was out for my last app.

Gavin.
