### ISSUE TITLE
App Crashes when using Apple Connection in Android sign in.

### ISSUE THREAD

**Issue by YonatanSegura97** [auth0/auth0-flutter#186]
### Checklist

- [ ] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi every one, I am facing with this issue, when I try to perform login with connection 'apple'. Only with Apple.

My Code:
`final result =
        await auth0.webAuthentication(scheme: "myScheme").login(
      audience: "MyAudience",
      scopes: scopes,
      parameters: {'connection':'apple'},
    );`

After that, my app crashes with this message. Only happens in Android.

E/AndroidRuntime(23780): java.lang.ClassCastException: java.lang.String cannot be cast to java.lang.Boolean
E/AndroidRuntime(23780): 	at com.auth0.auth0_flutter.UserProfileExtensionsKt.createUserProfileFromClaims(UserProfileExtensions.kt:46)
E/AndroidRuntime(23780): 	at com.auth0.auth0_flutter.request_handlers.web_auth.LoginWebAuthRequestHandler$handle$1.onSuccess(LoginWebAuthRequestHandler.kt:77)
E/AndroidRuntime(23780): 	at com.auth0.auth0_flutter.request_handlers.web_auth.LoginWebAuthRequestHandler$handle$1.onSuccess(LoginWebAuthRequestHandler.kt:66)
E/AndroidRuntime(23780): 	at com.auth0.android.provider.OAuthManager$resume$1$onSuccess$1.onSuccess(OAuthManager.kt:109)
E/AndroidRuntime(23780): 	at com.auth0.android.provider.OAuthManager$resume$1$onSuccess$1.onSuccess(OAuthManager.kt:107)
E/AndroidRuntime(23780): 	at com.auth0.android.provider.OAuthManager$assertValidIdToken$signatureVerifierCallback$1.onSuccess(OAuthManager.kt:173)
E/AndroidRuntime(23780): 	at com.auth0.android.provider.OAuthManager$assertValidIdToken$signatureVerifierCallback$1.onSuccess(OAuthManager.kt:151)
E/AndroidRuntime(23780): 	at com.auth0.android.provider.SignatureVerifier$1.onSuccess(SignatureVerifier.java:61)
E/AndroidRuntime(23780): 	at com.auth0.android.provider.SignatureVerifier$1.onSuccess(SignatureVerifier.java:56)
E/AndroidRuntime(23780): 	at com.auth0.android.request.internal.BaseRequest.start$lambda-2$lambda-0(BaseRequest.kt:74)
E/AndroidRuntime(23780): 	at com.auth0.android.request.internal.BaseRequest.$r8$lambda$thJncCgX0eAv7F6wYvOHkeDSO_0(Unknown Source:0)
E/AndroidRuntime(23780): 	at com.auth0.android.request.internal.BaseRequest$$ExternalSyntheticLambda1.run(Unknown Source:4)
E/AndroidRuntime(23780): 	at android.os.Handler.handleCallback(Handler.java:938)
E/AndroidRuntime(23780): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(23780): 	at android.os.Looper.loopOnce(Looper.java:233)
E/AndroidRuntime(23780): 	at android.os.Looper.loop(Looper.java:344)
E/AndroidRuntime(23780): 	at android.app.ActivityThread.main(ActivityThread.java:8212)
E/AndroidRuntime(23780): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(23780): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
E/AndroidRuntime(23780): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

### Reproduction

1. Configure Sign In with Apple
2. Try to perform login using Apple connection with webAuthentication

### auth0_flutter version

^1.0.2

### Flutter version

Stable

### Platform

Android

### Platform version(s)

Android 12

**Comment by Widcket** [comment]
@poovamraj could you please take a look?

**Comment by mkobuolys** [comment]
When can we expect this to be released? The issue crashes the app in production :/

**Comment by Widcket** [comment]
Hi @mkobuolys, we expect to release a new version next week.

**Comment by stevehobbsdev** [comment]
This has now been fixed in [v1.1.0](https://github.com/auth0/auth0-flutter/releases/tag/v1.1.0)
