### ISSUE TITLE
Check credentials without renewing them

### ISSUE THREAD

**Issue by KlausJokisuo** [auth0/auth0-flutter#192]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I would like to check current credentials without trying to renew them.

### Describe the ideal solution

Add option to current credentials method to not refresh credentials even when they are expired.

**Comment by Widcket** [comment]
Hi @KlausJokisuo, thanks for raising this. Could you please tell us more about your use case for this?

**Comment by KlausJokisuo** [comment]
@Widcket I would like to be able to check if the user has non expired refresh token. I will be working with offline first application, where I just need to check if refresh token is still valid and refresh the credentials when the app is back online.

**Comment by Widcket** [comment]
The validity of the refresh token cannot be checked without attempting to renew the credentials. However, the CredentialsManager's `hasValidCredentials()` method does check for the _presence_ of the refresh token, besides checking the validity of the access token: https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md#check-for-stored-credentials

**Comment by Widcket** [comment]
@KlausJokisuo does `hasValidCredentials()` work for your use case?

**Comment by KlausJokisuo** [comment]
@Widcket Thanks 🙌, I thought that the hasValidCredentials only checks for credentials.
