### ISSUE TITLE
Unable to use auth0 in Isolate

### ISSUE THREAD

**Issue by eliasjtg** [auth0/auth0-flutter#233]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm working in a isolate with background location, sending location to backend authenticated with Auth0.

`auth0.credentialsManager.credentials()`

This show the following exception:

```
E/MethodChannel#auth0.com/auth0_flutter/credentials_manager( 6251): Failed to handle method call
E/MethodChannel#auth0.com/auth0_flutter/credentials_manager( 6251): kotlin.UninitializedPropertyAccessException: lateinit property activity has not been initialized
E/MethodChannel#auth0.com/auth0_flutter/credentials_manager( 6251): 	at com.auth0.auth0_flutter.CredentialsManagerMethodCallHandler.getActivity(CredentialsManagerMethodCallHandler.kt:25)
E/MethodChannel#auth0.com/auth0_flutter/credentials_manager( 6251): 	at com.auth0.auth0_flutter.CredentialsManagerMethodCallHandler.onMethodCall(CredentialsManagerMethodCallHandler.kt:36)
E/MethodChannel#auth0.com/auth0_flutter/credentials_manager( 6251): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
E/MethodChannel#auth0.com/auth0_flutter/credentials_manager( 6251): 	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
E/MethodChannel#auth0.com/auth0_flutter/credentials_manager( 6251): 	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
E/MethodChannel#auth0.com/auth0_flutter/credentials_manager( 6251): 	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#auth0.com/auth0_flutter/credentials_manager( 6251): 	at android.os.Handler.handleCallback(Handler.java:907)
E/MethodChannel#auth0.com/auth0_flutter/credentials_manager( 6251): 	at android.os.Handler.dispatchMessage(Handler.java:105)
E/MethodChannel#auth0.com/auth0_flutter/credentials_manager( 6251): 	at android.os.Looper.loop(Looper.java:216)
E/MethodChannel#auth0.com/auth0_flutter/credentials_manager( 6251): 	at android.app.ActivityThread.main(ActivityThread.java:7625)
E/MethodChannel#auth0.com/auth0_flutter/credentials_manager( 6251): 	at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#auth0.com/auth0_flutter/credentials_manager( 6251): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:524)
E/MethodChannel#auth0.com/auth0_flutter/credentials_manager( 6251): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:987)
```

### Reproduction

Install plugin `background_locator_2` to run location background isolate
Run the app
Kill the app and attempt to get environment in isolate

### auth0_flutter version

1.1.0

### Flutter version

3.7.8

### Platform

Android

### Platform version(s)

9

**Comment by stevehobbsdev** [comment]
Thanks for the report @eliasjtg - is this something you can help us look into @poovamraj?

**Comment by poovamraj** [comment]
@eliasjtg The plugin requires instance of an activity (context actually) to fetch the credentials. Since it is not available in the background, the operation fails. 

Will it be possible for you to fetch the credentials before starting the background service and passing it there and using the service from there?

@stevehobbsdev for us to be not dependent on an `Activity` we have to pass an instance of context from `Auth0FlutterPlugin` which provides instance to an `applicationContext` which seem to be used by official Flutter team as mentioned [here](https://stackoverflow.com/a/60048705)

**Comment by poovamraj** [comment]
Hey @eliasjtg, we have implemented a fix for this. Can you checkout this PR in your project - https://github.com/auth0/auth0-flutter/pull/289

**Comment by poovamraj** [comment]
@eliasjtg since this is fixed in the PR mentioned above we will be closing this issue. The fix will be released in our next release.
