### ISSUE TITLE
 Use useEphemeralSession and logout without iOS’ native dialog

### ISSUE THREAD

**Issue by whitensane** [auth0/auth0-flutter#252]
### Checklist

- [X] I have looked into the [README](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

We want to use useEphemeralSession and we want to logout without iOS’ native dialog with text

"Application" want to Use "auth0" to Sign in

This allows the app and website to share information about you
For Flutter we use package

### Describe the ideal solution

 Use useEphemeralSession and logout without iOS’ native dialog

**Comment by Widcket** [comment]
Hi @whitensane, thanks for raising this.

This is explained in the FAQ: https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md#2-how-can-i-disable-the-ios-login-alert-box.
I'll go ahead and close this issue, as I believe that answers your question. Please let me kow if you'd prefer to reopen.
