### ISSUE TITLE
"Invalid date format" bug

### ISSUE THREAD

**Issue by Nirajn2311** [auth0/auth0-flutter#258]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [README](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com/c/sdks/5) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

If a user with a system language other than English tries using social login method(I've tested it with Google only), they are not logged in as the `expiresAt` value cannot be parsed due to it being in the system language. For example, if your mobile is set to use Arabic then the package tries parsing an arabic value. The ideal solution would be to parse the datetime while keeping in mind of a different locale being used by the system.

### Reproduction

1. Clone the example app
2. Change your phones language
3. Use a social login method through the web
4. See the error logged in console along with the datetime

### auth0_flutter version

1.1.0

### Flutter version

3.7.12

### Platform

Android, iOS

### Platform version(s)

Latest

**Comment by stevehobbsdev** [comment]
Thanks for raising. Seeing as you mention an example with Arabic, we have #238 that may fix this. Does the solution proposed in that PR look like it would solve your issue?

**Comment by Nirajn2311** [comment]
Yes that PR fixes this issue. Hope it gets merged soon.
