### ISSUE TITLE
Is it possible to add column created_at in Auth0.webAuthentication().login() method return (Credentials) in iOS?

### ISSUE THREAD

**Issue by geniallink** [auth0/auth0-flutter#275]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I'd like to have the created_at column to check if the user loggin in is a newly created user or not (I don't want control that in app side, because user can access app across other platforms).

I tried using custom claims but returns a sid in Credentials.user.customClaims, how can I use this sid to get the custom claims?

### Describe the ideal solution

Return the created_at field in class Credentials.user

### Alternatives and current workarounds

As a workaround I am doing a get request in the URL https://my-app.us.auth0.com/api/v2/users/[userId] using a management api key making, which is far from ideal to keep this key in the app (in my case, a mobile app).

**Comment by Widcket** [comment]
Hi @geniallink, thanks for raising this.

A custom claim is indeed the way to go for this. `Credentials.user.customClaims` [is a map](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter_platform_interface/lib/src/user_profile.dart#L103), so it should contain the custom claim, provided it was set using an Action/Rule.

Please check https://auth0.com/blog/adding-custom-claims-to-id-token-with-auth0-actions/ to learn more about adding custom claims to the ID token.

**Comment by Widcket** [comment]
Closing, as I believe the above answers your question. Please feel free to ping if you'd prefer to reopen.
