### ISSUE TITLE
compiling for iOS 12.0, but module 'Auth0' has a minimum deployment target of iOS 13.0

### ISSUE THREAD

**Issue by elemental21** [auth0/auth0-flutter#280]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm getting the same issue as this one for React Native. 
https://github.com/auth0/react-native-auth0/issues/646

Also reported here:
https://community.auth0.com/t/failed-to-create-ios-build-using-auth0-flutter/109630

The error:
Swift Compiler Error (Xcode): Compiling for iOS 12.0, but module 'Auth0' has a minimum deployment target of iOS 13.0: /Users/christopherrobinson/src/PicdmoFlutter/build/ios/Debug-DevEnvironment-iphoneos/Auth0/Auth0.framework/Modules/Auth0.swiftmodule/arm64-apple-ios.swiftmodule

### Reproduction

1. Do a pod update
2. Try to run your application with auth0-flutter

Receive this error:
Swift Compiler Error (Xcode): Compiling for iOS 12.0, but module 'Auth0' has a minimum deployment target of iOS 13.0: /Users/christopherrobinson/src/PicdmoFlutter/build/ios/Debug-DevEnvironment-iphoneos/Auth0/Auth0.framework/Modules/Auth0.swiftmodule/arm64-apple-ios.swiftmodule

### Additional context

What I've tried:

* Open your ios/Podfile file in a text editor.
* Look for a line that says platform :ios, '11.0' or a similar version number. This line sets the minimum iOS version for your project.

I set that value to 13,14,15 with no success.

What DID work but is not a good solution:

* Open the file: /Users/XXXXX/.pub-cache/hosted/pub.dev/auth0_flutter-1.2.1/ios/auth0_flutter.podspec.
* Edit the line:   s.platform     = :ios, '12.0' and set it to '13.0'

Flutter clean, build and it works. 

### auth0_flutter version

1.2.1

### Flutter version

3.7.11

### Platform

iOS

**Comment by Widcket** [comment]
Hi @elemental21, thanks for raising this.

You can work around this (until we put out another release) by setting specific versions of Auth0.swift, JTWDecode.swift, and SimpleKeychain in your Podfile. 
Or, by adding the following to your Podfile, as per https://github.com/auth0/react-native-auth0/issues/646#issuecomment-1593455702:

```ruby
installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
```
