### ISSUE TITLE
Missing namespace with android gradle tools version 8.0.0

### ISSUE THREAD

**Issue by KirkBushman** [auth0/auth0-flutter#281]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hello team, 
An error happens when migrating to the latest Android tools version: 

`com.android.tools.build:gradle:8.0.0`

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':auth0_flutter'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Please specify a namespace in the module's build.gradle file like so:

     android {
         namespace 'com.example.namespace'
     }

     If the package attribute is specified in the source AndroidManifest.xml, it can be migrated automatically to the namespace value in the build.gradle file using the AGP Upgrade Assistant; please refer to https://developer.android.com/studio/build/agp-upgrade-assistant for more information.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 24s
```

This is due to the fact that in the latest few versions, the namespace has been moved from the manifest to the gradle file. Seems pretty easy to fix, would you like a PR?

### Reproduction

- change tools version to 8.0.0 in an app with auth0_flutter
- get the error 

### auth0_flutter version

latest 

### Flutter version

latest

### Platform

Android

### Platform version(s)

Android 13 (API 33)

**Comment by Widcket** [comment]
Hi @KirkBushman, thanks for raising this.

@poovamraj could you please take a look?

**Comment by poovamraj** [comment]
Looks like I just found how Flutter is handling this here - https://github.com/flutter/flutter/pull/128360/files

I can create a PR for this to make things go quick. @KirkBushman would be happy if you can check it out.

**Comment by KirkBushman** [comment]
@poovamraj I just gave a look, and that fix should work fine, even though the final test would be importing the library on an 8.0.0 Android tools version. 

On a larger note, it might be risky in the future to have the library stay behind in versions, as things like this will keep on happening. Probably better to find a way to comply with security restrictions, rather than staying behind. :) 
Just my 2 cents.

**Comment by poovamraj** [comment]
Sure @KirkBushman we just want to ensure backward compatibility. We will be updating the version as soon as Flutter drops support :) 

The fix will be released soon in our next release. We will close this issue now. @Widcket will notify once the release is out.

**Comment by KirkBushman** [comment]
Hey @poovamraj @Widcket  despite the fix being merged several months ago, no new version was ever published. When is the next one planned for?

**Comment by Widcket** [comment]
@KirkBushman Apologies for the delay, I'll do a release by EOW.
