### ISSUE TITLE
Multiple prompt on every call back of login and logout

### ISSUE THREAD

**Issue by kapilb145** [auth0/auth0-flutter#283]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

In Android, When user logged in or logged out the call back url prompt two App icons for handling that call back.

### Reproduction

1.     final Credentials credentials = await auth0.webAuthentication(scheme: appScheme).login();
2.  await auth0.webAuthentication(scheme: appScheme).logout();

### auth0_flutter version

auth0_flutter: ^1.1.0

### Flutter version

3.10.5

### Platform

Android

### Platform version(s)

33

**Comment by Widcket** [comment]
Hi @kapilb145, thanks for raising this.

@poovamraj could you please take a look?

**Comment by poovamraj** [comment]
@kapilb145 Can you share the following details.

1. The callback URL you are using
2. The custom scheme you are using (This can be found in app/build.gradle - next to auth0Scheme)
3. The results for your package name when you run this command - `adb shell dumpsys package r`

The last command will give us all the Activities in your application that is using the intent to open your application. We are sure there is another Activity in your application that uses the same intent and this is why you are seeing 2 icons.

**Comment by kapilb145** [comment]
@poovamraj This turned out to be an issue with the manifest file. We need to support two different Auth0 tenants and the single manifest entry didn't solve for that. We were able to use the information provided on this issue (https://github.com/auth0/auth0-flutter/issues/265#issuecomment-1568744998) to resolve our problem. This issue can be closed. Thank you for your support
