### ISSUE TITLE
Login using webAuthentication is not working on Android.

### ISSUE THREAD

**Issue by HasanAlqaisi** [auth0/auth0-flutter#284]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I am trying to Implement login with google & apple. Everything is working great on IOS but not for Android.

This is what happens when trying to login with **Google**:
Only the First time It shows the list of my google accounts. When I click on one of them, the blank page is shown.
And no matter how much I try again the blank page will appear 

https://github.com/auth0/auth0-flutter/assets/57685540/8167f553-0618-4b1b-b222-06ae684d5919

And if I try login with Apple, the page will stuck like this:

https://github.com/auth0/auth0-flutter/assets/57685540/648bfa4e-6f5a-4a89-b17c-6941c42725d4

### Reproduction

1. Click on a button that calls this function:
```
await auth0.webAuthentication(scheme: "demo").login(
        parameters: {'connection': "apple"},
      )
```
And the rest is as described above.

### Additional context

logs:
```
D/TWAProviderPicker( 5722): Found TWA provider, finishing search: com.android.chrome
V/CustomTabsController( 5722): Trying to bind the service
V/CustomTabsController( 5722): Bind request result (com.android.chrome): true
V/CustomTabsController( 5722): Trying to bind the service
V/CustomTabsController( 5722): Bind request result (com.android.chrome): true
D/CustomTabsController( 5722): CustomTabs Service connected
D/CustomTabsController( 5722): Launching URI. Custom Tabs available: true
E/OpenGLRenderer( 5722): Unable to match the desired swap behavior.
W/Parcel  ( 5722): Expecting binder but got null!
```

Here's my setup for android:

strings.xml:
```
    <string name="com_auth0_domain">{http://***.com}</string>
    <string name="com_auth0_scheme">demo</string>
```

build.gradle:
`manifestPlaceholders += [auth0Domain: "@string/com_auth0_domain", auth0Scheme: "@string/com_auth0_scheme"]
`

In code:
```
  Auth0 auth0 = Auth0(
    'https://***.com', // domain
    '**********************', // clientID
  );
```

On button click:
```
await auth0.webAuthentication(scheme: "demo").login(
        parameters: {'connection': "apple"},
      )
```

### auth0_flutter version

1.2.1

### Flutter version

Channel stable, 3.10.5

### Platform

Android

### Platform version(s)

Android 13

**Comment by Widcket** [comment]
Hi @HasanAlqaisi, thanks for raising this.

@poovamraj could you please take a look?

**Comment by HasanAlqaisi** [comment]
I think this is happening because the application type in auth0 settings is SPA rather than native.
But why SPA is working fine with IOS?

**Comment by miguel-krasamo** [comment]
> I think this is happening because the application type in auth0 settings is SPA rather than native. But why SPA is working fine with an IOS simulator?

We are facing the same issue but we have the app settings configured to native

**Comment by HasanAlqaisi** [comment]
> > I think this is happening because the application type in auth0 settings is SPA rather than native. But why SPA is working fine with an IOS simulator?
> 
> We are facing the same issue but we have the app settings configured to native

I've made another application configured to native and it's working fine.

**Comment by HasanAlqaisi** [comment]
I managed to fix this. For me it wasn't about the application type, but the app domain.

**First issue** is that I added **https** to the domain by mistake.
And the **second one** is in strings.xml instead of:
`<string name="com_auth0_domain">@string/auth0_domain</string>`
I did:
`<string name="com_auth0_domain">{@string/auth0_domain}</string>`
