### ISSUE TITLE
Can auth0_flutter be used without Auth0?

### ISSUE THREAD

**Issue by markbeij** [auth0/auth0-flutter#287]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Is the flutter package auth0_flutter specific to Auth0 users, or is it also possible to use this package to connect with any identity provider that fully supports OAuth protocol?

### Reproduction

No reproduction steps; just a question

### Additional context

Asked this question on the [Auth0 forum](https://community.auth0.com/t/can-auth0-flutter-be-used-without-auth0/110659), but got the advise to ask the question here

### auth0_flutter version

any

### Flutter version

any

### Platform

Android, iOS, Web

**Comment by Widcket** [comment]
Hi @markbeij, thanks for raising this.

The auth0_flutter is specific to Auth0, I'm afraid it can't be used as a generic OpenID Connect client.

**Comment by markbeij** [comment]
Alright, thanks :+1:
