### ISSUE TITLE
Minor issue: Read me references wrong build.gradle

### ISSUE THREAD

**Issue by KingUgochukwu** [auth0/auth0-flutter#295]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Hi Auth0 Devs, There is a minor issue in the readme. 

The  instruction
_Open the android/build.gradle file and add the following manifest placeholders inside android > defaultConfig._

references the android/build.gradle but typically, flutter projects set their defaultConfig in the   android/app/build.gradle so it may be momentarily confusing

### Reproduction

Open Read Me

### auth0_flutter version

^1.2.1

### Flutter version

3.7.10

### Platform

Web

**Comment by Widcket** [comment]
Hi @KingUgochukwu, thanks for raising this, we really appreciate it.

I've created a brand new Flutter app and it is indeed under `/app`. I've raised https://github.com/auth0/auth0-flutter/pull/297 to fix it.
