### ISSUE TITLE
Flutter web not returning any credential after completion of login with audience. 

### ISSUE THREAD

**Issue by ranjitIN** [auth0/auth0-flutter#298]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

i am trying to perform login in flutter web by passing audience but the onload function does not return any credentials after completion of login with auth0. if i try to login with out passing audience it working fine. i also try this sample app i am facing the same issue. 

on load function 

  ```
@override
  void initState() {
    super.initState();
    auth0 = Auth0(domain,clinetId);
    auth0Web = Auth0Web(domain,clinetId);
    // webAuth =
    //     auth0!.webAuthentication(scheme: dotenv.env['AUTH0_CUSTOM_SCHEME']);

    if (kIsWeb) {
      auth0Web!.onLoad().then((final credentials) => setState(() {
            _output = credentials?.idToken ?? '';
            _isLoggedIn = credentials != null;
          }));
    }
  }
```

login function 

```
Future<void> webAuthLogin() async {
    String output = '';

    // Platform messages may fail, so we use a try/catch PlatformException.
    // We also handle the message potentially returning null.
    try {
      if (kIsWeb) {
        return auth0Web.loginWithRedirect(redirectUrl: 'http://localhost:3000',audience: audience);
      }

      final result = await webAuth.login();

      output = result.idToken;
    } catch (e) {
      output = e.toString();
    }

    setState(() {
      _isLoggedIn = true;
    });

    // If the widget was removed from the tree while the asynchronous platform
    // message was in flight, we want to discard the reply rather than calling
    // setState to update our non-existent appearance.
    if (!mounted) return;

    setState(() {
      _output = output;
    });
  }
```

### Reproduction

1. just pass audience on web login

### auth0_flutter version

1.2.1

### Flutter version

3.10.2

### Platform

Web

**Comment by Widcket** [comment]
Hi @ranjitIN, thanks for raising this.

I can only reproduce this when I don't configure the **Allowed Web Origins** URL:
<img width="574" alt="Screenshot 2023-08-02 at 11 43 37 PM" src="https://github.com/auth0/auth0-flutter/assets/5055789/f3f2be35-6690-4b22-9340-d48e6fb1b08f">
Have you configured this value in your Auth0 app's settings, as explained [here](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#%EF%B8%8F-web)?

**Comment by ranjitIN** [comment]
All these things are configured and it's working fine if I am not passing the audience . When I passed the audience the onload  function did not catch any credentials. 

The easiest way to reproduce this issue is to pass the audience when you try to login.

**Comment by Widcket** [comment]
If the Auth0 application is configured as described, I'm unable to reproduce on the [sample app](https://github.com/auth0-samples/auth0-flutter-samples/blob/main/sample/lib/example_app.dart):

https://github.com/auth0/auth0-flutter/assets/5055789/5a9b6f94-7f9e-4ba9-98b2-cec9c63ddce0

**Comment by ranjitIN** [comment]
is threre any update on this

**Comment by Widcket** [comment]
@ranjitIN you can't use HS256 with a mobile app, because it's a symmetric algorithm, meaning it requires a secret on both sides; but [mobile apps are public clients](https://auth0.com/docs/get-started/applications/confidential-and-public-applications), not confidential clients. You need to use an an asymmetric algorithm, like RS256.

**Comment by Widcket** [comment]
@ranjitIN if you open the developer tools, can you spot any errors coming back from the login page (on the "Networking" tab)?

**Comment by ranjitIN** [comment]
Yup There are some errors.  

https://github.com/auth0/auth0-flutter/assets/78366707/89122093-30b0-4491-8473-6815baf3c65b

**Comment by Widcket** [comment]
Thanks for the information. Could you please include the error response from the Dev Tools "Network" tab?

**Comment by ranjitIN** [comment]
Thanks for the support the issue is resolved after adding my web URL in allowed web origins. when is see the but its not throwing any exception. 
![image](https://github.com/auth0/auth0-flutter/assets/78366707/dcf40138-de11-4c27-9b98-a8091c1f74ff)

**Comment by ranjitIN** [comment]
thanks for the support but i am facing refresh token  web 
iam using loginWithPopup on flutter web but not able to fetch the refresh token is there anything i need to pass 
```
  credentials = await auth0.loginWithPopup(
            audience: audience,
            scopes: {'openid', 'profile', 'email', 'offline_access'});
```

![image](https://github.com/auth0/auth0-flutter/assets/78366707/369d8e7c-75d3-4161-90b6-15b7de52800f)

please let me know am i doing anything wrong

**Comment by Widcket** [comment]
@ranjitIN we use GitHub issues for bug reports and feature requests only. For help with usage, please raise a support ticket or refer to the [community forums](https://community.auth0.com/).
