### ISSUE TITLE
Could it be possible to use this package as InAppWebview 

### ISSUE THREAD

**Issue by ahmet-fennel** [auth0/auth0-flutter#301]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Currently, when invoking the authentication process, a pop-up opens in an external browser window. This behavior is not ideal for our user experience, even when useEphemeralSession: true is set. We're wondering the possibility of integrating the [InAppWebview package](https://pub.dev/packages/flutter_inappwebview) with the auth0-flutter library to enhance the user experience.

### Describe the ideal solution

Ideally, invoking`webAuthentication().login()` should direct users to an in-app page powered by InAppWebView. This would ensure that users remain within the app environment throughout the authentication process, providing a more seamless and integrated experience.

If there are technical constraints preventing this integration, we would greatly appreciate insights into those challenges. Such information would be invaluable in helping us understand and potentially seek alternative solutions.

Thank you for considering our feedback.

**Comment by Widcket** [comment]
Hi @ahmet-fennel,

Our mobile SDKs do not support in-app webviews. The current best practice for authorizing users on mobile apps requires using an external user-agent (that is, a browser).

<img width="819" alt="Screenshot 2023-08-17 at 9 28 30 PM" src="https://github.com/auth0/auth0-flutter/assets/5055789/6943741d-cd5c-40f6-9e46-2d028afef2a5">

See https://auth0.com/blog/oauth-2-best-practices-for-native-apps/. 

As such, this is something we won't add support for.
