### ISSUE TITLE
The request is made without validating claims. Enable claim validation by calling AuthenticationRequest#validateClaims()

### ISSUE THREAD

**Issue by susil07** [auth0/auth0-flutter#305]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The request is made without validating claims. Enable claim validation by calling AuthenticationRequest#validateClaims()

### Reproduction

by calling  auth0.api.login

### auth0_flutter version

auth0_flutter: ^1.2.1

### Flutter version

Flutter 3.7.7

### Platform

Android

**Comment by Widcket** [comment]
Hi @susil07, thanks for raising this. Please refer to https://github.com/auth0/auth0-flutter/issues/191#issuecomment-1386312980
