### ISSUE TITLE
Android dependency is imported dynamically, causing build issues.

### ISSUE THREAD

**Issue by parkgrrr** [auth0/auth0-flutter#313]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Last week, every branch new and old of our Android app no longer built due to a kotlin version build error After hours of pouring over merge requests, we realized the Auth0 flutter sdk was dynamically importing the Auth0 Android sdk. There is even a lint warning that is ignored in your sdk. If we would have had a hot fix needed, this would have halted our ability to release. Please lock the Android version for newer and older versions of the Auth0 sdk.

`    //noinspection GradleDynamicVersion
implementation 'com.auth0.android:auth0:2.+'`

Auth0 Android SDK that broke us: https://github.com/auth0/Auth0.Android/releases/tag/2.10.2

https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/android/build.gradle#L70C1-L71C49

### Reproduction

1. Add auth0 sdk to app
2. Wait for new Android sdk. version to be released
3. See any combination of build errors

### auth0_flutter version

1.1.0

### Flutter version

3.7.9

### Platform

Android

**Comment by poovamraj** [comment]
We have fixed this by locking our version here @parkgrrr - https://github.com/auth0/auth0-flutter/pull/311

You can follow this commit to fix the issue on your side- https://github.com/auth0/auth0-flutter/pull/311/commits/193c7260a5084f73e4d2aa11a60afd3f19663c4b

Sorry for the hassle.

**Comment by parkgrrr** [comment]
Thank you very much!

**Comment by parkgrrr** [comment]
Keeping this opened until it's merged. Thanks again.

**Comment by Widcket** [comment]
The version is now pinned in [v1.3.0](https://github.com/auth0/auth0-flutter/releases/tag/af-v1.3.0).
