### ISSUE TITLE
Logout does not support SafariViewController

### ISSUE THREAD

**Issue by MatthiasDh** [auth0/auth0-flutter#316]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Reading the docs it state that we can use the SafariViewController for authentication on login by providing
`safariViewController: const SafariViewController(),` to the login params.
      
However when doing the Logout, we can't specify that we want to use the safariViewController, as such, the credentials aren't cleared correctly.
      
When trying to log in again, it instant logs in as it is using the SafariViewController again and that has not been cleared.

I am not sure if I am missing something or that this is an actual bug/improvement.

### Reproduction

call `.login(safariViewController: const SafariViewController())` and enter your credentials.
call logout, this will not show the SafariViewController
call `.login(safariViewController: const SafariViewController())` again, this now instant logs in without asking for your credentials as it uses the SafariViewControllers cookies/cache (assumption)

### auth0_flutter version

^1.2,1

### Flutter version

3.10.0

### Platform

iOS

### Platform version(s)

17

**Comment by Widcket** [comment]
Hi @MatthiasDh, thanks for raising this.

This is intentional; according to SFSafariViewController's docs, it must be used "to visibly present information to users":

<img width="949" alt="Screenshot 2023-10-13 at 9 30 45 AM" src="https://github.com/auth0/auth0-flutter/assets/5055789/952aa669-f229-4e6e-bb7e-527b701bdea6">

This is the case for login, but not for logout. You can delete the stored credentials though (using the Credentials Manager) and use `'prompt': 'login'` to force the login page.

```dart
final credentials = await auth0.webAuthentication().login(
    useEphemeralSession: true,
    parameters: {
      'prompt': 'login'
    }); // Ignore the cookie (if present) and show the login page
```

Since the SFSafariViewController's cookies are scoped to your app, this should not pose an issue.

**Comment by MatthiasDh** [comment]
This makes sense, thanks for the reply and help.

Can confirm that the prompt login worked!
