### ISSUE TITLE
Upgrade to 1.4.0 fails

### ISSUE THREAD

**Issue by stefangaller** [auth0/auth0-flutter#368]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When upgrading to 1.4.0 the `auth0_flutter_platform_interface: 1.2.1` is not compatible anymore.
I think you missed upgrading the version in `pubspec.yaml`
<img width="418" alt="image" src="https://github.com/auth0/auth0-flutter/assets/1914504/8938e286-6559-429f-88f7-2e81568a9c65">

### Reproduction

* upgrade to 1.4.0
* auth0_flutter_platform_interface is still 1.2.1
* versions are not compatible

### auth0_flutter version

1.4.0

### Flutter version

any

### Platform

Android, iOS, Web

**Comment by Widcket** [comment]
Hi @stefangaller, thanks for reporting this. A PR with the fix is on the way.

**Comment by Widcket** [comment]
The fix is now out on [af-v1.4.1](https://github.com/auth0/auth0-flutter/releases/tag/af-v1.4.1). Thanks for your patience.
