### ISSUE TITLE
Error in upgrade version 1.4.0

### ISSUE THREAD

**Issue by victoralfonso920** [auth0/auth0-flutter#369]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

An error is generated when updating the package dependency to 1.4.0 where it does not detect the CompileSdkVersion

### Reproduction

update version package
run proyect in android devices

### Additional context

![imagen](https://github.com/auth0/auth0-flutter/assets/7407933/75f41153-cf8c-4d3e-b30d-51ce30d747e8)

### auth0_flutter version

1.4.0

### Flutter version

3.16.0

### Platform

Android

### Platform version(s)

13

**Comment by MilesAdamson** [comment]
I have the same issue

**Comment by victoralfonso920** [comment]
Downgrade to version 1.3.1, the fix does not happen there

**Comment by Widcket** [comment]
The fix is now out on [af-v1.4.1](https://github.com/auth0/auth0-flutter/releases/tag/af-v1.4.1). Thanks for reporting this.
