### ISSUE TITLE
Credentials toMap loses data. The user property is not populated into the map

### ISSUE THREAD

**Issue by MilesAdamson** [auth0/auth0-flutter#379]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

The following makes the error `type 'Null' is not a subtype of type 'Map<dynamic, dynamic>' in type cast`. Because `user` is required in `fromMap`, but not provided in `toMap`. `UserProfile` does not have a `toMap` method

1. get a Credentials object
2. turn it into a map with `toMap`
3. try to create a Credentials object from that map

### Reproduction

```
final result = Credentials.fromMap(credentials.toMap());
```

### auth0_flutter version

1.4.1

### Flutter version

3.16.3

### Platform

Android, iOS

### Platform version(s)

all

**Comment by Widcket** [comment]
Hi @MilesAdamson, thanks for raising this.

The UserProfile type currently does not support map conversion. We're aware of this, but do not have short-term plans to add it ATM. We'd welcome a PR adding it.

**Comment by MilesAdamson** [comment]
@Widcket I have a PR up
