### ISSUE TITLE
Error logging in in sandboxed app

### ISSUE THREAD

**Issue by Cpruce** [auth0/auth0-flutter#394]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

After logging in via google in a safari instance that gets spawned, I receive the following error 

```
flutter: ERROR: OTHER: An unexpected error occurred. CAUSE: Unable to complete the operation. CAUSE: Error Domain=NSPOSIXErrorDomain Code=1 "Operation not permitted" UserInfo={_NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <92FD24A9-5674-4FC4-B0DE-EFF882B8A03B>.<1>, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=1, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <92FD24A9-5674-4FC4-B0DE-EFF882B8A03B>.<1>"
), _NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en0[802.11], ipv4, dns, uses wifi}
```

I think the issue is returning data from the safari instance to the test app.

From what I've seen, we need to add to the entitlements to fix this but I haven't found one that works. I've tried `com.apple.security.device.serial` and `com.apple.security.network.client`, but no luck so far. 

Both ios and android work as intended. Only macos produces this issue.

### Reproduction

1. I believe [this demo](https://auth0.com/blog/get-started-with-flutter-authentication/#Set-Up-Auth0) is sufficient for reproducing the issue.
2. Build for macos.
3. Try logging in using a connection.

### auth0_flutter version

^1.5.0

### Flutter version

^3.13.0

### Platform

iOS

### Platform version(s)

macOS 14.2.1

**Comment by Widcket** [comment]
Hi @Cpruce, can you please confirm you can indeed reproduce this on the [example app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample)?

**Comment by Cpruce** [comment]
Hi @Widcket, thanks! The example app worked! I found what the issue was too :) 

I needed to set Outgoing Connections (Client) in App Sandbox (Debug and Profile)

<img width="626" alt="Screenshot 2024-01-02 at 7 22 52 PM" src="https://github.com/auth0/auth0-flutter/assets/2712171/7dbfe230-af7f-412d-8221-8e44e8a555c4">
