### ISSUE TITLE
Credentials seem to return wrong expire date

### ISSUE THREAD

**Issue by tikal** [auth0/auth0-flutter#459]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Post web login, Credentials object seems to be created with a date which differs from the UNIX timestamp contained in the accessToken: 

Example: 
DateTime: 2024-06-04T17:07:21.548Z  
UNIX Timesampt: 1717517241

This seems to be a TZ issue.

### Reproduction

Produce to a webLogin
Compare dates when object gets constructed

### auth0_flutter version

1.7.2

### Flutter version

3.19.3

### Platform

Android

**Comment by desusai7** [comment]
Hi @tikal, 

The Unix timestamp and the corresponding date shared by you are equivalent of each other itself right. Attaching a screenshot for you reference. 

<img width="707" alt="image" src="https://github.com/auth0/auth0-flutter/assets/48179357/5da04ed6-c330-43c5-9a42-92f4721769cd">

Please let me know if I am missing anything here.

**Comment by tikal** [comment]
Hi @desusai7, 
Sorry I might have copied the wrong data while creating the issue - you may want to try to reproduce the problem on your end to confirm.
