### ISSUE TITLE
Android documentation ask to overwrite the manifestPlaceholders and cause crashes on android when app start

### ISSUE THREAD

**Issue by AlexandreRoba** [auth0/auth0-flutter#481]
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

On the pub.dev home page of the package on the mobile android section it is recommended to add this line to the `app/build.graddle`:

```
manifestPlaceholders = [auth0Domain: "YOUR_AUTH0_DOMAIN", auth0Scheme: "https"] 
```

This will overwrite the manifestPlaceholders and remove all other place holders.

We should instead use:
```
manifestPlaceholders += [auth0Domain: "YOUR_AUTH0_DOMAIN", auth0Scheme: "https"]
```

### Reproduction

Follow the pud.dev installation and run android app.

### auth0_flutter version

latest

### Flutter version

latest

### Platform

Android

### Platform version(s)

mobile

**Comment by pmathew92** [comment]
@AlexandreRoba Thanks for bringing this to our notice. We will updated this change in our documentation

**Comment by pmathew92** [comment]
Have raised  #483 for the documentation change. 
Closing this for now. Please feel free to reopen if you any more concerns
